use_frameworks!

platform :ios, '8.0'

target 'WZReformerKeysKit_Example' do
  pod 'WZReformerKeysKit', :path => '../'

  target 'WZReformerKeysKit_Tests' do
    inherit! :search_paths

    
  end
end
